version: '3.8'

services:
  # Loadbalancer
  loadbalancer:
    build: ./loadbalancer/
    ports:
      - "80:80"
    depends_on:
      - front-node1
      - front-node2
      - front-node3
    networks:
      - frontend
      - backend
  # Presentation Tier 
  front-node1:
    build: ./presentation/website/
    ports:
      - "81:80"
    networks:
      - frontend
  front-node2:
    build: ./presentation/website/
    ports:
      - "82:80"
    networks:
      - frontend
  front-node3:
    build: ./presentation/website/
    ports:
      - "83:80"
    networks:
      - frontend
  # Business Tier
  business-node1:
    build: ./business/backend/
    ports:
      - "3001:3000"
    networks:
      - backend
  business-node2:
    build: ./business/backend/
    ports:
      - "3002:3000"
    networks:
      - backend
  business-node3:
    build: ./business/backend/
    ports:
      - "3003:3000"
    networks:
      - backend

networks:
  frontend:
  backend:
