version: '3.8'

services:
  # Presentation Tier 
  front-node1:
    build: ./presentation/website/
    ports:
      - "81:80"
  front-node2:
    build: ./presentation/website/
    ports:
      - "82:80"
  front-node3:
    build: ./presentation/website/
    ports:
      - "83:80"
  front-loadbalancer:
    build: ./presentation/loadbalancer/
    ports:
      - "80:80"
  # Business Tier
  business-node1:
    build: ./business/backend/
    ports:
      - "3001:3000"
  business-node2:
    build: ./business/backend/
    ports:
      - "3002:3000"
  business-node3:
    build: ./business/backend/
    ports:
      - "3003:3000"
  business-loadbalancer:
    build: ./business/loadbalancer/
    ports:
      - "3000:3000"
